# Generated by Django 3.1 on 2020-09-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200903_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderer',
        ),
        migrations.AddField(
            model_name='order',
            name='orderer_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
