# Generated by Django 3.1 on 2020-09-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderer_id',
        ),
        migrations.AddField(
            model_name='order',
            name='orderer',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
