# Generated by Django 3.1 on 2020-09-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200911_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderer',
        ),
    ]
