# Generated by Django 3.1 on 2020-09-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_orderer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderer',
            field=models.CharField(default='me', max_length=64),
            preserve_default=False,
        ),
    ]
