# Generated by Django 3.1 on 2020-09-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200911_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderer',
        ),
        migrations.AddField(
            model_name='order',
            name='orderer_id',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
