# Generated by Django 3.1 on 2020-09-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200901_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner_platter',
            name='image',
            field=models.CharField(default='menu/images/default.jpg', max_length=86),
        ),
        migrations.AddField(
            model_name='pasta',
            name='image',
            field=models.CharField(default='menu/images/default.jpg', max_length=86),
        ),
        migrations.AddField(
            model_name='regular_pizza',
            name='image',
            field=models.CharField(default='menu/images/default.jpg', max_length=86),
        ),
        migrations.AddField(
            model_name='salad',
            name='image',
            field=models.CharField(default='menu/images/default.jpg', max_length=86),
        ),
        migrations.AddField(
            model_name='sicilian_pizza',
            name='image',
            field=models.CharField(default='menu/images/default.jpg', max_length=86),
        ),
        migrations.AddField(
            model_name='sub',
            name='image',
            field=models.CharField(default='menu/images/default.jpg', max_length=86),
        ),
    ]
